language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: BADGE=linux
      addons:
        apt:
          packages:
            - libsdl1.2-dev
            - libgtk2.0-dev
      script:
        - true
    - os: osx
      env: BADGE=osx
      script:
        - true
